# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FilesCli < Formula
  desc "Official Pinata Files CLI written in Go"
  homepage "https://github.com/PinataCloud/files-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PinataCloud/files-cli/releases/download/v0.4.0/files-cli_Darwin_x86_64.tar.gz"
      sha256 "26665c584dd0890faa3e10394bc20133e821b738da5a6d4c731390776f39a0c0"

      def install
        bin.install "pinata"
      end
    end
    on_arm do
      url "https://github.com/PinataCloud/files-cli/releases/download/v0.4.0/files-cli_Darwin_arm64.tar.gz"
      sha256 "99ac08603ca07004010719a59540b88490bc9cafa35dbe6b4772ff7ced910cb3"

      def install
        bin.install "pinata"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/files-cli/releases/download/v0.4.0/files-cli_Linux_x86_64.tar.gz"
        sha256 "c927a1bf0aad68b2bbaca0763a73e7b10446752645063a61b8a6d6423144d307"

        def install
          bin.install "pinata"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/files-cli/releases/download/v0.4.0/files-cli_Linux_arm64.tar.gz"
        sha256 "bfc7b91b09c153f4ed6fe2944492c6eae9c55c7527104735c1826b11d32cddf2"

        def install
          bin.install "pinata"
        end
      end
    end
  end
end
