# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FilesCli < Formula
  desc "Official Pinata Files CLI written in Go"
  homepage "https://github.com/PinataCloud/files-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PinataCloud/files-cli/releases/download/v0.3.0/files-cli_Darwin_x86_64.tar.gz"
      sha256 "3ca527c644894236777c4612ac8bef3a7a1d349b69dee14d9f959b270cac488b"

      def install
        bin.install "pinata"
      end
    end
    on_arm do
      url "https://github.com/PinataCloud/files-cli/releases/download/v0.3.0/files-cli_Darwin_arm64.tar.gz"
      sha256 "9df233d86e6709105c237c88206f2e776ff9b57def6a3549a7aa936bed905447"

      def install
        bin.install "pinata"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/files-cli/releases/download/v0.3.0/files-cli_Linux_x86_64.tar.gz"
        sha256 "e33f5ae04fcef58abbf30f2fd4bbcbd39c87b1e2897c8cd0cc17b5eea3eae245"

        def install
          bin.install "pinata"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/files-cli/releases/download/v0.3.0/files-cli_Linux_arm64.tar.gz"
        sha256 "f9b7dae63790293575b99f5f81a0a565fa3a6aaf7f24131fec4161f87514c993"

        def install
          bin.install "pinata"
        end
      end
    end
  end
end
