# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FilesCli < Formula
  desc "Official Pinata Files CLI written in Go"
  homepage "https://github.com/PinataCloud/files-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/PinataCloud/files-cli/releases/download/v0.1.4/files-cli_Darwin_x86_64.tar.gz"
      sha256 "74c00d7de3d82737b08678fc2b3f484386738f8ea52b68bd8ab4160209fa1151"

      def install
        bin.install "pinata"
      end
    end
    on_arm do
      url "https://github.com/PinataCloud/files-cli/releases/download/v0.1.4/files-cli_Darwin_arm64.tar.gz"
      sha256 "c6b384670707198a63aaaa3f1b181014d775cc5f3b5b20aafdf409074b46a900"

      def install
        bin.install "pinata"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/files-cli/releases/download/v0.1.4/files-cli_Linux_x86_64.tar.gz"
        sha256 "4db8958b7ab4db6cfcbae5ae61539ce849405c44c3b01f1d27685e0c057faa23"

        def install
          bin.install "pinata"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/PinataCloud/files-cli/releases/download/v0.1.4/files-cli_Linux_arm64.tar.gz"
        sha256 "a4ba1a9be98ecccb6270562193558837b0d49721a6059415b2e9b555fb533cd4"

        def install
          bin.install "pinata"
        end
      end
    end
  end
end
